---
- hosts: webserver
  remote_user: test100
  become: yes
  vars:
   pkg1: httpd
  vars_files:
   - abc.yml
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
     register: result
     ignore_errors: yes
   - name: copy
     copy: src=index.html dest=/var/www/html
     notify: restart
   - name: start
     service: name=httpd state=started
   - debug: var=result
  handlers:
    - name: restart
      service: name=httpd state=restarted

